{
    'name': "Freezoner Custom",
    'author': "BeshoyWageh",
    'version': '16.0',
    'depends': ['base', 'hr_expense', 'sale', 'stock', 'project', 'product', 'sale_project', 'hr',
                'employee_salesperson_task', 'mail', 'documents', 'documents_project', 'cabinet_directory',
                'mass_mailing', 'utm', 'partner_organization', 'payment_status_in_sale'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/cron.xml',
        'data/action.xml',
        'wizard/required_document_wizard.xml',
        'wizard/task_assignees_wizard.xml',
        'wizard/return_project_wizard.xml',
        'wizard/remarks_wizard.xml',
        'views/document_request.xml',
        'views/partner.xml',
        'views/documents.xml',
        'views/document.xml',
        'views/account_move.xml',
        'views/expense.xml',
        'views/product.xml',
        'views/project.xml',
        'views/task.xml',
        'views/crm.xml',
        'views/sale.xml',
        'views/rating.xml',
        'views/sale_portal.xml',
        'data/mails.xml',
        'data/data.xml',
        'data/survey_mail.xml',
        'data/crm_mails.xml',
        'wizard/task_wizard.xml',
        'wizard/task_next_wizard.xml',
        'wizard/sale_crm.xml',
        'wizard/update_fields.xml',
    ],
    'assets': {
       'web.assets_qweb': [
            '/freezoner_custom/static/src/xml/share_documents.xml',  # Register XML
        ],
        'web.assets_backend': [
            '/freezoner_custom/static/src/css/style.scss',
            '/freezoner_custom/static/src/js/documents_share_patch.js',
            '/freezoner_custom/static/src/xml/share_documents.xml',  # Register XML
            '/freezoner_custom/static/src/xml/documents.xml',
        ],
    },
}
